//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RingBearer.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RingBearer.Core.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About.
        /// </summary>
        public static string AboutPageTitleMAUI {
            get {
                return ResourceManager.GetString("AboutPageTitleMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Entry.
        /// </summary>
        public static string AddEntryPageTitleMAUI {
            get {
                return ResourceManager.GetString("AddEntryPageTitleMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add new entry.
        /// </summary>
        public static string AddEntrySubtitle {
            get {
                return ResourceManager.GetString("AddEntrySubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Creates or updates an entry with the provided values..
        /// </summary>
        public static string AddOrUpdHelpText1 {
            get {
                return ResourceManager.GetString("AddOrUpdHelpText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a To remove a value, include its prefix without any data..
        /// </summary>
        public static string AddOrUpdHelpText2 {
            get {
                return ResourceManager.GetString("AddOrUpdHelpText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ex: add entryKey -p -n -u clear all fileds..
        /// </summary>
        public static string AddOrUpdHelpText3 {
            get {
                return ResourceManager.GetString("AddOrUpdHelpText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apply Language.
        /// </summary>
        public static string ApplyLangButtonTextMAUI {
            get {
                return ResourceManager.GetString("ApplyLangButtonTextMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The assembly name cannot be null or empty..
        /// </summary>
        public static string AssemblyNameNullError {
            get {
                return ResourceManager.GetString("AssemblyNameNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change password.
        /// </summary>
        public static string ChangePasswordButtonTextMAUI {
            get {
                return ResourceManager.GetString("ChangePasswordButtonTextMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter new password....
        /// </summary>
        public static string ChangePasswordPlaceHolderMAUI {
            get {
                return ResourceManager.GetString("ChangePasswordPlaceHolderMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the new password.
        /// </summary>
        public static string ChangePasswordSubtitleTextMAUI {
            get {
                return ResourceManager.GetString("ChangePasswordSubtitleTextMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close.
        /// </summary>
        public static string CloseAppTextMAUI {
            get {
                return ResourceManager.GetString("CloseAppTextMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Command cannot be empty. Please enter a valid command..
        /// </summary>
        public static string CommandNullError {
            get {
                return ResourceManager.GetString("CommandNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm Deletion.
        /// </summary>
        public static string ConfirmDeletionHeaderMAUI {
            get {
                return ResourceManager.GetString("ConfirmDeletionHeaderMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to delete the selected entries?.
        /// </summary>
        public static string ConfirmDeletionMessageMAUI {
            get {
                return ResourceManager.GetString("ConfirmDeletionMessageMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        public static string ConfirmDeletionNoButtonMAUI {
            get {
                return ResourceManager.GetString("ConfirmDeletionNoButtonMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yes.
        /// </summary>
        public static string ConfirmDeletionYesButtonMAUI {
            get {
                return ResourceManager.GetString("ConfirmDeletionYesButtonMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm password must be at least 3 characters long..
        /// </summary>
        public static string ConfirmPasswordLengthMAUI {
            get {
                return ResourceManager.GetString("ConfirmPasswordLengthMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm new password....
        /// </summary>
        public static string ConfirmPasswordPlaceHolderMAUI {
            get {
                return ResourceManager.GetString("ConfirmPasswordPlaceHolderMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm password is required..
        /// </summary>
        public static string ConfirmPasswordRequiredMAUI {
            get {
                return ResourceManager.GetString("ConfirmPasswordRequiredMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        public static string DeletePageTitleMAUI {
            get {
                return ResourceManager.GetString("DeletePageTitleMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        public static string DeleteSelectedButtonTextMAUI {
            get {
                return ResourceManager.GetString("DeleteSelectedButtonTextMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to read the file. It may be corrupted or have an invalid format. Please check if the file is password-protected..
        /// </summary>
        public static string DeserializationFailedException {
            get {
                return ResourceManager.GetString("DeserializationFailedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Developed by.
        /// </summary>
        public static string DevelopedByTextMAUI {
            get {
                return ResourceManager.GetString("DevelopedByTextMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelled.
        /// </summary>
        public static string DisplayAlertCancelTitleMAUI {
            get {
                return ResourceManager.GetString("DisplayAlertCancelTitleMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string DisplayAlertErrorTitleMAUI {
            get {
                return ResourceManager.GetString("DisplayAlertErrorTitleMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Info.
        /// </summary>
        public static string DisplayAlertInfoTitleMAUI {
            get {
                return ResourceManager.GetString("DisplayAlertInfoTitleMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OK.
        /// </summary>
        public static string DisplayAlertOkButtonTextMAUI {
            get {
                return ResourceManager.GetString("DisplayAlertOkButtonTextMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Success.
        /// </summary>
        public static string DisplayAlertSuccessTitleMAUI {
            get {
                return ResourceManager.GetString("DisplayAlertSuccessTitleMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit Entry.
        /// </summary>
        public static string EditEntryPageTitleMAUI {
            get {
                return ResourceManager.GetString("EditEntryPageTitleMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit entry.
        /// </summary>
        public static string EditEntrySubtitle {
            get {
                return ResourceManager.GetString("EditEntrySubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} entries imported!.
        /// </summary>
        public static string EntriesImportedMAUI {
            get {
                return ResourceManager.GetString("EntriesImportedMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entries List.
        /// </summary>
        public static string EntriesListPageTitleMAUI {
            get {
                return ResourceManager.GetString("EntriesListPageTitleMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a │                Entries List                     │.
        /// </summary>
        public static string EntriesListTitle {
            get {
                return ResourceManager.GetString("EntriesListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New entry added successfully..
        /// </summary>
        public static string EntryAdded {
            get {
                return ResourceManager.GetString("EntryAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An entry with the key: &quot;{0}&quot; already exists..
        /// </summary>
        public static string EntryAlreadyExists {
            get {
                return ResourceManager.GetString("EntryAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entry deleted successfully..
        /// </summary>
        public static string EntryDeleted {
            get {
                return ResourceManager.GetString("EntryDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entry with the specified key not found..
        /// </summary>
        public static string EntryNotFound {
            get {
                return ResourceManager.GetString("EntryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entry cannot be null..
        /// </summary>
        public static string EntryNullError {
            get {
                return ResourceManager.GetString("EntryNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entry details.
        /// </summary>
        public static string EntryPageTitleMAUI {
            get {
                return ResourceManager.GetString("EntryPageTitleMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entry updated successfully..
        /// </summary>
        public static string EntryUpdated {
            get {
                return ResourceManager.GetString("EntryUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exiting manager, press a key to finish....
        /// </summary>
        public static string ExitApp {
            get {
                return ResourceManager.GetString("ExitApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Press [ Esc  ] to exit..
        /// </summary>
        public static string ExitEscApp {
            get {
                return ResourceManager.GetString("ExitEscApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Export.
        /// </summary>
        public static string ExportButtonTextMAUI {
            get {
                return ResourceManager.GetString("ExportButtonTextMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exported file.
        /// </summary>
        public static string ExportedFilePathTitleMAUI {
            get {
                return ResourceManager.GetString("ExportedFilePathTitleMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Export format is not supported..
        /// </summary>
        public static string ExportFormatNotSupportedException {
            get {
                return ResourceManager.GetString("ExportFormatNotSupportedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please navigate to the folder manually: {0}.
        /// </summary>
        public static string ExportInfoMessageMAUI {
            get {
                return ResourceManager.GetString("ExportInfoMessageMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password (if applicable).
        /// </summary>
        public static string ExportPlaceHolderMAUI {
            get {
                return ResourceManager.GetString("ExportPlaceHolderMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Export entries.
        /// </summary>
        public static string ExportSubtitleMAUI {
            get {
                return ResourceManager.GetString("ExportSubtitleMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File not found..
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File path cannot be null or empty..
        /// </summary>
        public static string FilePahtNullError {
            get {
                return ResourceManager.GetString("FilePahtNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File path cannot be null or empty..
        /// </summary>
        public static string FilePathNullError {
            get {
                return ResourceManager.GetString("FilePathNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Storage access is required to import files..
        /// </summary>
        public static string FileStoragePerminsionTextMAUI {
            get {
                return ResourceManager.GetString("FileStoragePerminsionTextMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permission required.
        /// </summary>
        public static string FileStoragePermisionTitleMAUI {
            get {
                return ResourceManager.GetString("FileStoragePermisionTitleMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Key.
        /// </summary>
        public static string HeaderKeyTable {
            get {
                return ResourceManager.GetString("HeaderKeyTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notes.
        /// </summary>
        public static string HeaderNotesTable {
            get {
                return ResourceManager.GetString("HeaderNotesTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string HeaderPassTable {
            get {
                return ResourceManager.GetString("HeaderPassTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ║                                 Keep it secret, keep it safe.                                             ║.
        /// </summary>
        public static string HeaderSubtitle {
            get {
                return ResourceManager.GetString("HeaderSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Keep it secret, keep it safe..
        /// </summary>
        public static string HeaderSubtitleMAUI {
            get {
                return ResourceManager.GetString("HeaderSubtitleMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User.
        /// </summary>
        public static string HeaderUserTable {
            get {
                return ResourceManager.GetString("HeaderUserTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adds a new entry to the file..
        /// </summary>
        public static string HelpAddExplanation {
            get {
                return ResourceManager.GetString("HelpAddExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Changes the master password..
        /// </summary>
        public static string HelpCmkExplanation {
            get {
                return ResourceManager.GetString("HelpCmkExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deletes an entry from the file..
        /// </summary>
        public static string HelpDelExplanation {
            get {
                return ResourceManager.GetString("HelpDelExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Closes the manager..
        /// </summary>
        public static string HelpExitExplanation {
            get {
                return ResourceManager.GetString("HelpExitExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Searches for entries that match the word.
        /// </summary>
        public static string HelpFilterExplanation1 {
            get {
                return ResourceManager.GetString("HelpFilterExplanation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a in either the key or the value..
        /// </summary>
        public static string HelpFilterExplanation2 {
            get {
                return ResourceManager.GetString("HelpFilterExplanation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Looks up an entry in the file..
        /// </summary>
        public static string HelpGetExplanation {
            get {
                return ResourceManager.GetString("HelpGetExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Displays help for a specific command..
        /// </summary>
        public static string HelpHelpExplanation_ {
            get {
                return ResourceManager.GetString("HelpHelpExplanation ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Available languages: .
        /// </summary>
        public static string HelpLangExplanation {
            get {
                return ResourceManager.GetString("HelpLangExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shows all entries in the file..
        /// </summary>
        public static string HelpLsExplanation {
            get {
                return ResourceManager.GetString("HelpLsExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AVAILABLE COMMANDS.
        /// </summary>
        public static string HelpSubtitle {
            get {
                return ResourceManager.GetString("HelpSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter [ h ] to see the list of commands..
        /// </summary>
        public static string HelpTitle {
            get {
                return ResourceManager.GetString("HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Updates an existing entry in the file..
        /// </summary>
        public static string HelpUpdateExplanation {
            get {
                return ResourceManager.GetString("HelpUpdateExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Import.
        /// </summary>
        public static string ImportButtonTextMAUI {
            get {
                return ResourceManager.GetString("ImportButtonTextMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No entries to import..
        /// </summary>
        public static string ImportEntriesNullError {
            get {
                return ResourceManager.GetString("ImportEntriesNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Import/Export.
        /// </summary>
        public static string ImportExportPageTitleMAUI {
            get {
                return ResourceManager.GetString("ImportExportPageTitleMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password (if applicable).
        /// </summary>
        public static string ImportPlaceHolderMAUI {
            get {
                return ResourceManager.GetString("ImportPlaceHolderMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Import entries.
        /// </summary>
        public static string ImportSubtitleMAUI {
            get {
                return ResourceManager.GetString("ImportSubtitleMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid entry. Please check the entered data..
        /// </summary>
        public static string InvalidEntry {
            get {
                return ResourceManager.GetString("InvalidEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid master key. Please check your password and try again..
        /// </summary>
        public static string InvalidMasterKeyError {
            get {
                return ResourceManager.GetString("InvalidMasterKeyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Key cannot be null or empty..
        /// </summary>
        public static string KeyNullError {
            get {
                return ResourceManager.GetString("KeyNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter a key....
        /// </summary>
        public static string KeyPlaceholderMAUI {
            get {
                return ResourceManager.GetString("KeyPlaceholderMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Keyword cannot be null or empty..
        /// </summary>
        public static string KeywordNullError {
            get {
                return ResourceManager.GetString("KeywordNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language changed successfully. Restart the app to see the changes..
        /// </summary>
        public static string LanguageChanged {
            get {
                return ResourceManager.GetString("LanguageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select Language.
        /// </summary>
        public static string LanguageChangeTitleMAUI {
            get {
                return ResourceManager.GetString("LanguageChangeTitleMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The selected language is not supported. (Av:.
        /// </summary>
        public static string LanguageNotSuported {
            get {
                return ResourceManager.GetString("LanguageNotSuported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language.
        /// </summary>
        public static string LanguagePageTitleMAUI {
            get {
                return ResourceManager.GetString("LanguagePageTitleMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to load entries from the file..
        /// </summary>
        public static string LoadFileError {
            get {
                return ResourceManager.GetString("LoadFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        public static string LoginBtnText {
            get {
                return ResourceManager.GetString("LoginBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        public static string LoginPageTitleMAUI {
            get {
                return ResourceManager.GetString("LoginPageTitleMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Master key changed successfully. Please remember it..
        /// </summary>
        public static string MasterKeyChanged {
            get {
                return ResourceManager.GetString("MasterKeyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error changing master key..
        /// </summary>
        public static string MasterKeyChangedErrorMAUI {
            get {
                return ResourceManager.GetString("MasterKeyChangedErrorMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Master key changed successfully. .
        /// </summary>
        public static string MasterKeyChangedSuccessMAUI {
            get {
                return ResourceManager.GetString("MasterKeyChangedSuccessMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Master key cannot be null or empty..
        /// </summary>
        public static string MasterKeyNullError {
            get {
                return ResourceManager.GetString("MasterKeyNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your password: .
        /// </summary>
        public static string MasterKeyText {
            get {
                return ResourceManager.GetString("MasterKeyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your password....
        /// </summary>
        public static string MasterKeyTextMAUI {
            get {
                return ResourceManager.GetString("MasterKeyTextMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No entries found..
        /// </summary>
        public static string NoEntries {
            get {
                return ResourceManager.GetString("NoEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OK.
        /// </summary>
        public static string NoEntriesSelectedButtonMAUI {
            get {
                return ResourceManager.GetString("NoEntriesSelectedButtonMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No Entries Selected.
        /// </summary>
        public static string NoEntriesSelectedHeaderMAUI {
            get {
                return ResourceManager.GetString("NoEntriesSelectedHeaderMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please select at least one entry to delete..
        /// </summary>
        public static string NoEntriesSelectedMessageMAUI {
            get {
                return ResourceManager.GetString("NoEntriesSelectedMessageMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No entries to export..
        /// </summary>
        public static string NoEntriesToExportMessageMAUI {
            get {
                return ResourceManager.GetString("NoEntriesToExportMessageMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No entries were imported..
        /// </summary>
        public static string NoEntriesToImportMAUI {
            get {
                return ResourceManager.GetString("NoEntriesToImportMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No file selected..
        /// </summary>
        public static string NoFileSelectedTextMAUI {
            get {
                return ResourceManager.GetString("NoFileSelectedTextMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must add the key of the entry (eg: get myEntry).
        /// </summary>
        public static string NoKeyOnGetError {
            get {
                return ResourceManager.GetString("NoKeyOnGetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please provide a language code (e.g., &apos;en&apos;, &apos;es&apos;)..
        /// </summary>
        public static string NoLanguageOnGetError {
            get {
                return ResourceManager.GetString("NoLanguageOnGetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add extra notes....
        /// </summary>
        public static string NotesPlaceholderMAUI {
            get {
                return ResourceManager.GetString("NotesPlaceholderMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opening folders is not supported on this platform..
        /// </summary>
        public static string OpenFolderNotSuportedMAUI {
            get {
                return ResourceManager.GetString("OpenFolderNotSuportedMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password must be at least 3 characters long..
        /// </summary>
        public static string PasswordLengthMAUI {
            get {
                return ResourceManager.GetString("PasswordLengthMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Passwords do not match..
        /// </summary>
        public static string PasswordMatchMAUI {
            get {
                return ResourceManager.GetString("PasswordMatchMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password cannot be null or empty..
        /// </summary>
        public static string PasswordNullError {
            get {
                return ResourceManager.GetString("PasswordNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change Password.
        /// </summary>
        public static string PasswordPageTitleMAUI {
            get {
                return ResourceManager.GetString("PasswordPageTitleMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the password....
        /// </summary>
        public static string PasswordPlaceHolderMAUI {
            get {
                return ResourceManager.GetString("PasswordPlaceHolderMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password is required for encrypted export..
        /// </summary>
        public static string PasswordRequiredForEncryptedExportException {
            get {
                return ResourceManager.GetString("PasswordRequiredForEncryptedExportException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password is required..
        /// </summary>
        public static string PasswordRequiredMAUI {
            get {
                return ResourceManager.GetString("PasswordRequiredMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Important: If you forget your password, you will not be able to recover your information and you will have to reinstall the application..
        /// </summary>
        public static string PasswordWarningText {
            get {
                return ResourceManager.GetString("PasswordWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plain text cannot be null or empty..
        /// </summary>
        public static string PlainTextNullError {
            get {
                return ResourceManager.GetString("PlainTextNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Press any key to continue....
        /// </summary>
        public static string PressKeyToContinue {
            get {
                return ResourceManager.GetString("PressKeyToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        public static string SaveButtonTextMAUI {
            get {
                return ResourceManager.GetString("SaveButtonTextMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to save entries to the file..
        /// </summary>
        public static string SaveFileError {
            get {
                return ResourceManager.GetString("SaveFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search....
        /// </summary>
        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select All.
        /// </summary>
        public static string SelectAllTextMAUI {
            get {
                return ResourceManager.GetString("SelectAllTextMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        public static string SettingsPageTitleMAUI {
            get {
                return ResourceManager.GetString("SettingsPageTitleMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loading....
        /// </summary>
        public static string SpinnerTextMAUI {
            get {
                return ResourceManager.GetString("SpinnerTextMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unrecognized command. Try again..
        /// </summary>
        public static string UnrecognizedCommand {
            get {
                return ResourceManager.GetString("UnrecognizedCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unsupported file type..
        /// </summary>
        public static string UnsupportedFileErrorMAUI {
            get {
                return ResourceManager.GetString("UnsupportedFileErrorMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username cannot be null or empty..
        /// </summary>
        public static string UsernameNullError {
            get {
                return ResourceManager.GetString("UsernameNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter a user name...
        /// </summary>
        public static string UserNamePlaceholderMAUI {
            get {
                return ResourceManager.GetString("UserNamePlaceholderMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warning: If the file contains entries with the same key, the existing data will be overwritten..
        /// </summary>
        public static string WarningImportTextMAUI {
            get {
                return ResourceManager.GetString("WarningImportTextMAUI", resourceCulture);
            }
        }
    }
}
